name: Continuous Integration
on:
  push:
    branches:
      - '**'
jobs:
  build:
    name: Build
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-20.04
          - windows-latest
          - macos-13
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Gradle build
        run: ./gradlew build
      - name: Upload Artifacts
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v4
        with:
          path: |
            **/build/distributions/*
            **/build/reports/*
  e2e-integration:
    name: End-to-end Integration test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: adopt
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download Distribution
        uses: actions/download-artifact@v4
        with:
          name: artifact
          path: artifact
      - name: Extract Distribution
        uses: ihiroky/extract-action@v1
        with:
          file_path: artifact/similarity/build/distributions/similarity.tar
          extract_dir: dist
      - name: Test Similarity
        run: |
          dist/similarity/bin/similarity muse1.txt muse2.txt 3 > e2e-output.txt
          grep -xq "Similarity:0.9000325774286236" e2e-output.txt
      - name: Upload Output
        uses: actions/upload-artifact@v4
        with:
          name: standard-output
          path: e2e-output.txt